Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic
  FunctionalMethods:
    - new

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false
