Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic
